import fs from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";
import matter from "gray-matter";
import MarkdownIt from "markdown-it";
import sanitizeHtml from "sanitize-html";

const here = path.dirname(fileURLToPath(import.meta.url));
const frontendRoot = path.resolve(here, "..");
const contentRoot = path.join(frontendRoot, "content");
const generatedRoot = path.join(frontendRoot, "src", "generated");
const markdown = new MarkdownIt({ html: true, linkify: true, typographer: true });

const cleanHtml = (value) =>
  sanitizeHtml(value || "", {
    allowedTags: sanitizeHtml.defaults.allowedTags.concat(["img", "figure", "figcaption"]),
    allowedAttributes: {
      ...sanitizeHtml.defaults.allowedAttributes,
      a: ["href", "name", "target", "rel"],
      img: ["src", "alt", "title", "width", "height", "loading"],
    },
    allowedSchemes: ["http", "https", "mailto", "tel"],
    transformTags: {
      a: (_tagName, attribs) => ({
        tagName: "a",
        attribs: {
          ...attribs,
          ...(attribs.target === "_blank" ? { rel: "noopener noreferrer" } : {}),
        },
      }),
    },
  });

const readJson = (filename) => JSON.parse(fs.readFileSync(filename, "utf8"));
const pageFiles = fs
  .readdirSync(path.join(contentRoot, "pages"))
  .filter((filename) => filename.endsWith(".json"))
  .sort();
const articleFiles = fs
  .readdirSync(path.join(contentRoot, "articles"))
  .filter((filename) => filename.endsWith(".md"))
  .sort();

const siteContent = readJson(path.join(contentRoot, "site.json"));
const pages = Object.fromEntries(
  pageFiles.map((filename) => {
    const page = readJson(path.join(contentRoot, "pages", filename));
    const required = ["slug", "title", "seoTitle", "seoDescription", "canonicalPath"];
    for (const field of required) {
      if (!String(page[field] || "").trim()) {
        throw new Error(`${filename} is missing required field: ${field}`);
      }
    }
    return [page.slug, { ...page, content: cleanHtml(markdown.render(page.content || "")) }];
  })
);

const seenSlugs = new Set();
const posts = articleFiles
  .map((filename) => {
    const source = fs.readFileSync(path.join(contentRoot, "articles", filename), "utf8");
    const { data, content } = matter(source);
    const slug = String(data.slug || "").trim();
    if (!slug) throw new Error(`${filename} is missing a slug`);
    if (seenSlugs.has(slug)) throw new Error(`Duplicate article slug: ${slug}`);
    seenSlugs.add(slug);
    return {
      id: slug,
      title: String(data.title || "").trim(),
      slug,
      excerpt: String(data.excerpt || "").trim(),
      status: data.status === "published" ? "published" : "draft",
      published_at: data.publishedAt || null,
      hero_image_url: data.heroImage || "",
      seo_title: data.seoTitle || data.title || "",
      seo_description: data.seoDescription || data.excerpt || "",
      content: cleanHtml(markdown.render(content)),
    };
  })
  .filter((post) => post.status === "published")
  .sort((a, b) => new Date(b.published_at || 0) - new Date(a.published_at || 0));

fs.mkdirSync(generatedRoot, { recursive: true });
const output = `// Generated by scripts/generate-content.mjs. Do not edit directly.\n` +
  `export const SITE_CONTENT = ${JSON.stringify(siteContent, null, 2)};\n` +
  `export const PAGES = ${JSON.stringify(pages, null, 2)};\n` +
  `export const POSTS = ${JSON.stringify(posts, null, 2)};\n`;
fs.writeFileSync(path.join(generatedRoot, "content.js"), output, "utf8");

console.log(`Generated ${Object.keys(pages).length} pages and ${posts.length} published articles.`);
